name: "zip-push"
author: "itskop520@gmail.com"
description: "Zip source code and push it to a remote server"
branding:
  icon: "info"
  color: "green"
inputs:
  zip-file-name:
    required: true
    description: "name of zip file to be pushed"
  username:
    required: true
    description: "http basic auth username"
  password:
    required: true
    description: "http basic auth password"
  url:
    required: true
    description: "url endpoint to upload file"
  upload-file-filed-name:
    required: true
    description: "form field name when upload file"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --zip-file-name=${{ inputs.zip-file-name }}
    - --username=${{ inputs.username }}
    - --password=${{ inputs.password }}
    - --url=${{ inputs.url }}
    - --upload-file-filed-name=${{ inputs.upload-file-filed-name }}
