name: Test Self action
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test zip it action
        uses: ./
        with:
          zip-file-name: "test.zip"
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          url: "https://static.sandbox.com.np/upload"
          upload-file-filed-name: "file"
          query-params: "folder_name=test"
